name 'kodius-recepies'
maintainer 'Kresimir Bojcic'
maintainer_email 'kresimir.bojcic@krokodil.hr'
license 'all_rights'
description 'Installs/Configures kodius-recepies'
long_description 'Installs/Configures kodius-recepies'
version '0.1.0'
depends 'magic_shell'
